name: "Watch SQL Queries"
description: "This action watches traffic to the database to record what SQL queries are executed."
inputs:
  SQL_PROXY_API_ADDRESS:
    description: "The port on which the sql proxy api is running"
    required: true
  DB_CONNECTION_STRING:
    description: "The connection string to the database"
    required: true
  DEFAULT_DATABASE:
    description: "The default database to use"
    required: true
  GITHUB_REPOSITORY:
    description: "The github repository to use"
    required: true
  GITHUB_TOKEN:
    description: "The github token to use"
    required: true
outputs:
  sql-queries:
    description: "A list of all the sql queries executed."
    value: ${{ steps.get-sql-data.outputs.sql-queries }}
  queries-diff:
    description: "A diff of SQL executed"
    value: ${{ steps.get-sql-data.outputs.queries-diff }}
  schema:
    description: "The full schema of the database"
    value: ${{ steps.get-sql-data.outputs.schema }}
  schema-diff:
    description: "A diff of the database schema"
    value: ${{ steps.get-sql-data.outputs.schema-diff }}
runs:
  using: "composite"
  steps:
    - name: Checkout action repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.action_repository }}
        ref: ${{ github.action_ref }}

    - name: Run recon
      id: get-sql-data
      shell: bash
      env:
        SQL_PROXY_API_ADDRESS: ${{ inputs.SQL_PROXY_API_ADDRESS }}
        DB_CONNECTION_STRING: ${{ inputs.DB_CONNECTION_STRING }}
        DEFAULT_DATABASE: ${{ inputs.DEFAULT_DATABASE }}
        GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        chmod +x ./recon
        ./recon
