name: "Watch SQL Queries"
description: "This action watches traffic to the database to record what SQL queries are executed."
inputs:
  SQL_PROXY_API_PORT:
    description: "The port on which the sql proxy api is running"
    required: true
  DB_CONNECTION_STRING:
    description: "The connection string to the database"
    required: true
  DEFAULT_DATABASE:
    description: "The default database to use"
    required: true
  GITHUB_REPOSITORY:
    description: "The github repository to use"
    required: true
  GITHUB_TOKEN:
    description: "The github token to use"
    required: true
outputs:
  sql-queries:
    description: "A list of all the sql queries executed."
  queries-diff:
    description: "A diff of SQL executed"
  schema:
    description: "The full schema of the database"
  schema-diff:
    description: "A diff of the database schema"
runs:
  using: "docker"
  image: "Dockerfile"
